.github/workflows/ci.yml
.gitignore
.zcodeignore
LICENSE
README.md
docker-compose.yml
docs/deploy.md
docs/user-guide.md
ops/backup.sh
package-lock.json
package.json
server/.env.example
server/dist/app.module.js
server/dist/app.module.js.map
server/dist/common/decorators/current-user.decorator.js
server/dist/common/decorators/current-user.decorator.js.map
server/dist/common/decorators/public.decorator.js
server/dist/common/decorators/public.decorator.js.map
server/dist/common/filters/all-exceptions.filter.js
server/dist/common/filters/all-exceptions.filter.js.map
server/dist/common/guards/admin.guard.js
server/dist/common/guards/admin.guard.js.map
server/dist/common/guards/approval.guard.js
server/dist/common/guards/approval.guard.js.map
server/dist/common/guards/jwt-auth.guard.js
server/dist/common/guards/jwt-auth.guard.js.map
server/dist/common/middleware/csrf.middleware.js
server/dist/common/middleware/csrf.middleware.js.map
server/dist/config/configuration.js
server/dist/config/configuration.js.map
server/dist/main.js
server/dist/main.js.map
server/dist/modules/admin/admin-users.controller.js
server/dist/modules/admin/admin-users.controller.js.map
server/dist/modules/admin/admin.module.js
server/dist/modules/admin/admin.module.js.map
server/dist/modules/audit/audit.module.js
server/dist/modules/audit/audit.module.js.map
server/dist/modules/audit/audit.service.js
server/dist/modules/audit/audit.service.js.map
server/dist/modules/auth/auth.controller.js
server/dist/modules/auth/auth.controller.js.map
server/dist/modules/auth/auth.module.js
server/dist/modules/auth/auth.module.js.map
server/dist/modules/auth/auth.service.js
server/dist/modules/auth/auth.service.js.map
server/dist/modules/auth/dto/auth.dto.js
server/dist/modules/auth/dto/auth.dto.js.map
server/dist/modules/health/health.controller.js
server/dist/modules/health/health.controller.js.map
server/dist/modules/health/health.module.js
server/dist/modules/health/health.module.js.map
server/dist/modules/lectures/dto/lecture.dto.js
server/dist/modules/lectures/dto/lecture.dto.js.map
server/dist/modules/lectures/lectures.controller.js
server/dist/modules/lectures/lectures.controller.js.map
server/dist/modules/lectures/lectures.module.js
server/dist/modules/lectures/lectures.module.js.map
server/dist/modules/lectures/lectures.service.js
server/dist/modules/lectures/lectures.service.js.map
server/dist/modules/lectures/results.helper.js
server/dist/modules/lectures/results.helper.js.map
server/dist/modules/presentations/conversion.constants.js
server/dist/modules/presentations/conversion.constants.js.map
server/dist/modules/presentations/conversion.processor.js
server/dist/modules/presentations/conversion.processor.js.map
server/dist/modules/presentations/converter.service.js
server/dist/modules/presentations/converter.service.js.map
server/dist/modules/presentations/dto/poll.dto.js
server/dist/modules/presentations/dto/poll.dto.js.map
server/dist/modules/presentations/polls.controller.js
server/dist/modules/presentations/polls.controller.js.map
server/dist/modules/presentations/polls.service.js
server/dist/modules/presentations/polls.service.js.map
server/dist/modules/presentations/portable.service.js
server/dist/modules/presentations/portable.service.js.map
server/dist/modules/presentations/presentations.controller.js
server/dist/modules/presentations/presentations.controller.js.map
server/dist/modules/presentations/presentations.module.js
server/dist/modules/presentations/presentations.module.js.map
server/dist/modules/presentations/presentations.service.js
server/dist/modules/presentations/presentations.service.js.map
server/dist/modules/presentations/slides.controller.js
server/dist/modules/presentations/slides.controller.js.map
server/dist/modules/presentations/slides.service.js
server/dist/modules/presentations/slides.service.js.map
server/dist/modules/vote/dto/vote.dto.js
server/dist/modules/vote/dto/vote.dto.js.map
server/dist/modules/vote/vote-logic.js
server/dist/modules/vote/vote-logic.js.map
server/dist/modules/vote/vote.controller.js
server/dist/modules/vote/vote.controller.js.map
server/dist/modules/vote/vote.module.js
server/dist/modules/vote/vote.module.js.map
server/dist/modules/vote/vote.service.js
server/dist/modules/vote/vote.service.js.map
server/dist/prisma/prisma.module.js
server/dist/prisma/prisma.module.js.map
server/dist/prisma/prisma.service.js
server/dist/prisma/prisma.service.js.map
server/jest.config.js
server/nest-cli.json
server/package.json
server/prisma/migrations/20261003214427_init/migration.sql
server/prisma/migrations/20261004104548_user_moderation/migration.sql
server/prisma/migrations/20261004131553_lecture_reveal/migration.sql
server/prisma/migrations/20261004134045_pending_reveal/migration.sql
server/prisma/migrations/20261004161658_presentation_course/migration.sql
server/prisma/migrations/migration_lock.toml
server/prisma/schema.prisma
server/prisma/seed.ts
server/scripts/fix-mojibake-titles.ts
server/scripts/make-sample-pptx.ts
server/src/app.module.ts
server/src/common/decorators/current-user.decorator.ts
server/src/common/decorators/public.decorator.ts
server/src/common/filters/all-exceptions.filter.ts
server/src/common/guards/admin.guard.ts
server/src/common/guards/approval.guard.ts
server/src/common/guards/jwt-auth.guard.ts
server/src/common/middleware/csrf.middleware.ts
server/src/config/configuration.ts
server/src/main.ts
server/src/modules/admin/admin-users.controller.ts
server/src/modules/admin/admin.module.ts
server/src/modules/audit/audit.module.ts
server/src/modules/audit/audit.service.ts
server/src/modules/auth/auth.controller.ts
server/src/modules/auth/auth.module.ts
server/src/modules/auth/auth.service.ts
server/src/modules/auth/dto/auth.dto.ts
server/src/modules/health/health.controller.ts
server/src/modules/health/health.module.ts
server/src/modules/lectures/dto/lecture.dto.ts
server/src/modules/lectures/lectures.controller.ts
server/src/modules/lectures/lectures.module.ts
server/src/modules/lectures/lectures.service.ts
server/src/modules/lectures/results.helper.ts
server/src/modules/presentations/conversion.constants.ts
server/src/modules/presentations/conversion.processor.ts
server/src/modules/presentations/converter.service.ts
server/src/modules/presentations/dto/poll.dto.ts
server/src/modules/presentations/polls.controller.ts
server/src/modules/presentations/polls.service.ts
server/src/modules/presentations/portable.service.ts
server/src/modules/presentations/presentations.controller.ts
server/src/modules/presentations/presentations.module.ts
server/src/modules/presentations/presentations.service.ts
server/src/modules/presentations/slides.controller.ts
server/src/modules/presentations/slides.service.ts
server/src/modules/vote/dto/vote.dto.ts
server/src/modules/vote/vote-logic.ts
server/src/modules/vote/vote.controller.ts
server/src/modules/vote/vote.module.ts
server/src/modules/vote/vote.service.ts
server/src/prisma/prisma.module.ts
server/src/prisma/prisma.service.ts
server/storage-test/originals/01ec09f0-fd3a-4e7b-8fb9-e3a780daffeb/original.pdf
server/storage-test/originals/03f0db9d-1824-4e4c-b5e8-acc63dfc5a1c/original.pdf
server/storage-test/originals/07e28b6c-65af-4e48-9495-403296b7b0ae/original.pdf
server/storage-test/originals/0b34c786-3fb3-4fab-be4b-99c0c356c870/original.pdf
server/storage-test/originals/13935572-2fc5-4c0d-ac28-ddcc18aa7860/original.pdf
server/storage-test/originals/1ed356cf-0207-4c93-8173-6cb3fc66fa0c/original.pdf
server/storage-test/originals/20aaf661-dc9f-49a8-ad35-7023e51f577e/original.pdf
server/storage-test/originals/22ecd851-2b96-469c-b1d9-47e3df057a01/original.pdf
server/storage-test/originals/291f79b2-84d8-4174-bb17-d903bf460be2/original.pdf
server/storage-test/originals/332351a0-bd61-48f6-8f38-ce78454340ec/original.pdf
server/storage-test/originals/43c79ecc-9679-4b2a-97b6-f8f188c475df/original.pdf
server/storage-test/originals/465cef68-bae9-4d2e-aa11-21d2556e0ab4/original.pdf
server/storage-test/originals/4fc5c900-8f3a-4ea8-80fa-d613cfb3f086/original.pdf
server/storage-test/originals/5e725f91-c477-4318-821c-cf4116a1de58/original.pdf
server/storage-test/originals/611395d8-d953-440a-8e49-1e0ffd5900f1/original.pdf
server/storage-test/originals/62957e22-f03e-4a2f-8d84-777c186d68ea/original.pdf
server/storage-test/originals/6cc58e65-9c55-484d-8afa-6a0fe9e92652/original.pdf
server/storage-test/originals/6d23025a-16b7-41d7-b7a9-10d418d8d229/original.pdf
server/storage-test/originals/6f5ca6d3-1df3-400f-ba80-a99897b88741/original.pdf
server/storage-test/originals/70cf952c-2c56-421d-a532-287cfe939c1f/original.pdf
server/storage-test/originals/79504818-790a-4935-9a9c-ec16f8f8d8f5/original.pdf
server/storage-test/originals/7fae6398-779b-4d6f-8a93-a462fb8f2167/original.pdf
server/storage-test/originals/8a76b79e-ad62-422e-adf3-5698fae856e3/original.pdf
server/storage-test/originals/8d571fa4-8918-465b-96f7-0cfb839b7460/original.pdf
server/storage-test/originals/a3090354-6951-45cd-abda-3b7825012d84/original.pdf
server/storage-test/originals/ad551410-2518-41cb-b848-db029cdd79b1/original.pdf
server/storage-test/originals/b9fa7e9f-0804-49f6-a49a-878c074c4a53/original.pdf
server/storage-test/originals/bbcc2c95-2736-492c-9d0c-27f269e5a338/original.pdf
server/storage-test/originals/bc1a469d-ecbe-452b-b0b3-bc9a892eedf9/original.pdf
server/storage-test/originals/be7c10da-f3d5-42c4-87b1-1be2b884d686/original.pdf
server/storage-test/originals/c54d3f0d-d151-4f3f-8f6b-5283ce459dbc/original.pdf
server/storage-test/originals/c69c15b2-e23e-49f0-bc23-9f8fe3f2cba6/original.pdf
server/storage-test/originals/c7b27af1-d568-46eb-bf02-671ba60cc323/original.pdf
server/storage-test/originals/c8950cd3-e4dc-4976-ba7b-d175fdee7431/original.pdf
server/storage-test/originals/cc4dc83f-c565-447b-b330-d2b362d2f31c/original.pdf
server/storage-test/originals/cfeb0d36-6a4f-4867-86c5-7f7e724b0732/original.pdf
server/storage-test/originals/d2bb8354-7375-4c64-a116-ce8ece84c580/original.pdf
server/storage-test/originals/db426e16-ac18-4e1b-b817-361a4f0c84fa/original.pdf
server/storage-test/originals/db8c8454-eaaa-44fa-b34b-7526848c894d/original.pdf
server/storage-test/originals/dc93dfb4-efd9-46a9-835e-8d3f6e73c74f/original.pdf
server/storage-test/originals/dd5efe15-2068-4865-bc7f-905825ffc2b0/original.pdf
server/storage-test/originals/df33836f-f9a0-4e30-a855-a8a35a1f8ccf/original.pdf
server/storage-test/originals/dfbea3b3-4c79-4c22-8617-09127725c5e2/original.pdf
server/storage-test/originals/e690bb32-90ba-48eb-93a3-fcbc9608871c/original.pdf
server/storage-test/originals/ede651cf-5f89-4421-b3a5-29af5ee28fd8/original.pdf
server/storage-test/originals/efa17ae9-d2b5-4cb6-a707-29875dd66569/original.pdf
server/storage-test/originals/f772633d-4e8e-4ed8-bf41-6f7b46af0cd0/original.pdf
server/tests/global-setup.ts
server/tests/helpers.ts
server/tests/integration/flow.test.ts
server/tests/setup-env.ts
server/tests/unit/results.helper.test.ts
server/tests/unit/vote-logic.test.ts
server/tsconfig.build.json
server/tsconfig.json
upload/PulseCheck.svg
web/dist/assets/index-BZwnE7dO.css
web/dist/assets/index-CvgbOkza.js
web/dist/index.html
web/index.html
web/package.json
web/src/api/client.ts
web/src/api/types.ts
web/src/assets/pulsecheck-logo.svg
web/src/components/CopySlidesDialog.tsx
web/src/components/Layout.tsx
web/src/components/Logo.tsx
web/src/components/PollBuilder.tsx
web/src/components/ResultsView.tsx
web/src/index.css
web/src/main.tsx
web/src/pages/AdminUsers.tsx
web/src/pages/LectureDetail.tsx
web/src/pages/Lectures.tsx
web/src/pages/Login.tsx
web/src/pages/Present.tsx
web/src/pages/PresentationDetail.tsx
web/src/pages/Presentations.tsx
web/src/pages/Vote.tsx
web/src/state/auth.tsx
web/tsconfig.json
web/vite.config.ts
